# Generated by Django 4.1 on 2022-09-28 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 28, 11, 21, 46, 57594)),
        ),
    ]
