# Generated by Django 4.1 on 2022-09-28 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_mytask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 28, 11, 46, 21, 809283)),
        ),
    ]
